// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: blog.proto

package server

import (
	"context"

	"gotask/task4_gozero/rpc/blog/blog"
	"gotask/task4_gozero/rpc/blog/internal/logic"
	"gotask/task4_gozero/rpc/blog/internal/svc"
)

type BlogServer struct {
	svcCtx *svc.ServiceContext
	blog.UnimplementedBlogServer
}

func NewBlogServer(svcCtx *svc.ServiceContext) *BlogServer {
	return &BlogServer{
		svcCtx: svcCtx,
	}
}

func (s *BlogServer) CreatePost(ctx context.Context, in *blog.CreatePostRequest) (*blog.CreatePostResponse, error) {
	l := logic.NewCreatePostLogic(ctx, s.svcCtx)
	return l.CreatePost(in)
}

func (s *BlogServer) GetPost(ctx context.Context, in *blog.GetPostRequest) (*blog.GetPostResponse, error) {
	l := logic.NewGetPostLogic(ctx, s.svcCtx)
	return l.GetPost(in)
}

func (s *BlogServer) ListPosts(ctx context.Context, in *blog.ListPostsRequest) (*blog.ListPostsResponse, error) {
	l := logic.NewListPostsLogic(ctx, s.svcCtx)
	return l.ListPosts(in)
}

func (s *BlogServer) UpdatePost(ctx context.Context, in *blog.UpdatePostRequest) (*blog.UpdatePostResponse, error) {
	l := logic.NewUpdatePostLogic(ctx, s.svcCtx)
	return l.UpdatePost(in)
}

func (s *BlogServer) DeletePost(ctx context.Context, in *blog.DeletePostRequest) (*blog.DeletePostResponse, error) {
	l := logic.NewDeletePostLogic(ctx, s.svcCtx)
	return l.DeletePost(in)
}

func (s *BlogServer) CreateComment(ctx context.Context, in *blog.CreateCommentRequest) (*blog.CreateCommentResponse, error) {
	l := logic.NewCreateCommentLogic(ctx, s.svcCtx)
	return l.CreateComment(in)
}

func (s *BlogServer) ListComments(ctx context.Context, in *blog.ListCommentsRequest) (*blog.ListCommentsResponse, error) {
	l := logic.NewListCommentsLogic(ctx, s.svcCtx)
	return l.ListComments(in)
}
