// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"net/http"

	"gotask/task4_gozero/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/posts",
				Handler: CreatePostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/posts",
				Handler: ListPostsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/posts/:id",
				Handler: GetPostHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/posts/:id",
				Handler: UpdatePostHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/posts/:id",
				Handler: DeletePostHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/posts/:id/comments",
				Handler: CreateCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/posts/:id/comments",
				Handler: ListCommentsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/register",
				Handler: RegisterHandler(serverCtx),
			},
		},
	)
}
