// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type CommentResp struct {
	Id        int64  `json:"id"`
	Content   string `json:"content"`
	UserId    int64  `json:"userId"`
	PostId    int64  `json:"postId"`
	CreatedAt int64  `json:"createdAt"`
}

type CreateCommentReq struct {
	Content string `json:"content"`
}

type CreatePostReq struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type ListCommentsResp struct {
	Comments []CommentResp `json:"comments"`
}

type ListPostsReq struct {
	Page int32 `form:"page,default=1"`
	Size int32 `form:"size,default=10"`
}

type ListPostsResp struct {
	Posts []PostResp `json:"posts"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token  string `json:"token"`
	UserId int64  `json:"userId"`
}

type PostResp struct {
	Id        int64  `json:"id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	UserId    int64  `json:"userId"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type RegisterResp struct {
	UserId int64 `json:"userId"`
}

type UpdatePostReq struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}
